print("Today's date is")
input()
print("Breakfast calories?")
breakfast = int(input())
print("Lunch calories?")
lunch = int(input())
print("Dinner calories?")
dinner = int(input())
print("Snack calories")
snacks = int(input())
print("Total calories of the day " + str(breakfast + lunch + dinner + snacks))