# Generated by Django 3.2.8 on 2021-10-21 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0002_auto_20211021_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='intakeDate',
            new_name='intake_date',
        ),
        migrations.AddField(
            model_name='dog',
            name='adoption_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
